### ISSUE TITLE
Tmux Version of Nightfly Theme?

### ISSUE THREAD

**Issue by erwin** [bluz71/vim-nightfly-colors#42]
Has anyone put together some Tmux settings that look good with Nightfly?

While Tmux itself seems to support true-color, I can't seem to get actual hex color codes to work with Tmux's fg=,bg= color options, it seems to just pick an approximate (somewhat matching but not exact) color for the actual Tmux UI (even though true color apps inside of tmux work fine).

Anyway, even if somebody's got a 256color theme that just is a nice match with nightfly that would be awesome. Right now I've got a tmux theme that's kind of close and so it clashes really badly...

**Comment by erwin** [comment]
It seems with tmux 3.3a you no longer have to manually override any terminal settings for true color support.

You should make sure to have the `tmux` `terminfo` files from your distro installed though

```
/usr/share/terminfo/t/tmux
/usr/share/terminfo/t/tmux-256color
/usr/share/terminfo/t/tmux-direct
/usr/share/terminfo/x/xterm+tmux2
/usr/share/terminfo/x/xterm+tmux
```

I found a fantastic blog post going through the process to make a 24-bit Dracula style color theme for tmux.

https://cassidy.codes/blog/2019-08-03-tmux-colour-theme/

Note that the author uses [tmux-mem-cpu-load](https://github.com/thewtex/tmux-mem-cpu-load) which was a bit more statusline bloat than I could handle...

Loosely based on the Dracula theme, I was able to make a Tmux `nightfly` theme that I think is a good start. Hopefully @bluz71 uses tmux sometimes (it's such an awesome complement to [tmate](https://tmate.io/)) for pair programming) and can take the raw details here and improve the color selection a bit.

I really like the use of `#{?client_prefix,#[bg=#66d1ff]#[fg=#092236],}` to toggle colors when the tmux prefix key is active... Really makes the UI less mysterious :-)

#### Normal Tmux Appearance

![image](https://user-images.githubusercontent.com/11534217/206653379-f77a8a68-bee0-4b4b-a357-8e17208e1fa1.png)

#### When Tmux Prefix is active (after you hit Ctr+a, or Ctrl+b...)
![image](https://user-images.githubusercontent.com/11534217/206653442-902a24f9-3a67-43eb-8e42-66a5c90b8145.png)


```tmux
##################################################################
# Nightfly Tmux Theme Idea 
#################################################################
set -g message-style bg='#65d1ff',fg='#092236'
set -g message-command-style bg='#ffda7b',fg='#000000'

set -g status-style bg='#2c3043',fg='#bd93f9'
set -g status-interval 1

# Status Left
set -g  status-left '#[bg=#011627]#[fg=#acb4c2]#{?client_prefix,#[bg=#66d1ff]#[fg=#092236],} ☺ '
set -ga status-left '#[bg=#2c3043]#[fg=#65d1ff] #{?window_zoomed_flag, ↕ ,   }'

# Status Center (Windows)
set-window-option -g window-status-style fg='#65d1ff',bg=default
set-window-option -g window-status-current-style fg='#65d1ff',bg='#282a36'

set -g  window-status-current-format "#[fg=#2c3043]#[bg=#011627]#{?client_prefix,#[bg=#66d1ff],}"
set -ga window-status-current-format "#[fg=#acb4c2]#[bg=#011627]#{?client_prefix,#[bg=#66d1ff]#[fg=#092236],} #I #W "
set -ga window-status-current-format "#[fg=#011627]#[bg=#2c3043]#{?client_prefix,#[fg=#66d1ff],}"
set -g  window-status-format         "#[fg=#2c3043]#[bg=#2c3043]"
set -ga window-status-format         "#[fg=#f8f8f2]#[bg=#2c3043] #I #W #[fg=#2c3043]"

# Status Right
#set -g  status-right '#[fg=#8be9fd,bg=#2c3043]#[fg=#2c3043,bg=#8be9fd] #(tmux-mem-cpu-load -g 0 -m 2 -a 1 --interval 2) '
set -g  status-right '#[fg=#011627,bg=#2c3043]#{?client_prefix,#[fg=#66d1ff],}'
set -ga status-right '#[fg=#acb4c2,bg=#011627]#{?client_prefix,#[bg=#66d1ff]#[fg=#092236],}'
set -ga status-right '#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") '
set -ga status-right '#[fg=#282a36,bg=#011628]#{?client_prefix,#[bg=#66d1ff],}'
set -ga status-right '#[fg=#f8f8f2,bg=#282a36] %a %H:%M:%S '
set -ga status-right '#[fg=#011627,bg=#282a36]#{?client_prefix,#[fg=#66d1ff],}'
set -ga status-right '#[fg=#acb4c2,bg=#011627]#{?client_prefix,#[bg=#66d1ff]#[fg=#092236],} %Y-%m-%d '
```

**Comment by bluz71** [comment]
I do use tmux.

But I use a [moonfly](https://github.com/bluz71/vim-moonfly-colors) color palette as listed in [my Alacritty configuration](https://github.com/bluz71/dotfiles/blob/master/terminal_configs/alacritty_linux.yml#L60) and [my tmux configuration](https://github.com/bluz71/dotfiles/blob/master/tmux.conf#L153).

This configuration, works well enough with nightfly and moonfly, for me.

**Comment by bluz71** [comment]
I think we can close this since you now have a tmux configuration you are happy with.

Best regards.
