### ISSUE TITLE
Cant enable theme

### ISSUE THREAD

**Issue by HappyCthulhu** [bluz71/vim-nightfly-colors#44]
Hi! First thing, that i wanna 2 tell about: your project is great, thx 4 it

Your theme working well in Firenvim (in browser). But i cant activate it outside of Chrome... Idk, why. I even removed all text from `init.vim`, besides:
```
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
Plug 'bluz71/vim-nightfly-colors'
call plug#end()

colorscheme nightfly "must be after plugin installation section
```

That didnt help... 

System: Arch/i3
My nvim-config: https://github.com/HappyCthulhu/.config/blob/master/nvim/init.vim

**Comment by bluz71** [comment]
You need to set both `termguicolors` and the `colorscheme` in `~/.config/nvim/init.vim` as follows:

```viml
set termguicolors 

call plug#begin()
Plug 'bluz71/vim-nightfly-colors'
call plug#end()

colorscheme nightfly
```

Make sure you call `:PlugInstall` inside Neovim to install the plugin itself into the vim-plug directory of `~/.local/share/nvim/plugged`; please check this directory to make sure the theme is installed. Maybe you did not do this particular step.

If you do all of the above the colorscheme will work.

Best regards.
