### ISSUE TITLE
How to customize (or fix) some elements

### ISSUE THREAD

**Issue by boydkelly** [bluz71/vim-nightfly-colors#45]
Hi,
I love the theme colors and contrast!  Thank you!
I know beauty is in the eye of the beholder...

I find the window borders an separators a bit wide and taking up too much real estate, especially vertical windows,  and Nvim-tree and toggle-term.  For Telescope the border lines and title seem to lack just a bit of contrast.  I was trying to get a 'flat' no border look for telescope as described here:  

https://www.reddit.com/r/neovim/comments/se377t/telescopenvim_looks_neat/

see also: https://github.com/nvim-telescope/telescope.nvim/blob/39b12d84e86f5054e2ed98829b367598ae53ab41/plugin/telescope.lua#L27-L30

I tried for hours putting the snippets in the telescope.lua config, as well as trying to integrate directly into nightfly. 
(I don't know that it would be benefical to include all the code here;  Maybe this has become a feature request...!)

It does seem to me that there are a few Telescope items missing in the nightfly/init.lua config, notably:

```
  | highlight(0, "TelescopeSelectionCaret", { fg = p.red, bg = bg_visual })    
  | highlight(0, "TelescopePromptTitle", { fg = p.orange, bg = "NONE" })    
  | highlight(0, "TelescopeResultsTitle", { fg = p.orange, bg = "NONE" })    
  | highlight(0, "TelescopePreviewTitle", { fg = p.orange, bg = "NONE" })    
  | highlight(0, "TelescopePromptCounter", { fg = p.red, bg = "NONE" })    
  | highlight(0, "TelescopePreviewHyphen", { fg = p.red, bg = "NONE" })    

```

I was also fiddling around with:

````
highlight(0, "WinSeparator", { link = "VertSplit" })
highlight(0, "VertSplit", { fg = border, bg = "NONE" })
````

I have added a couple of screen shots to show the difference between nightfly and 'another' popular theme.  Note its not the colors I am wanting to change but the border.

example flat no border for Telegram:
![Screenshot from 2023-01-08 10-29-21](https://user-images.githubusercontent.com/3412972/211192310-1d047262-2c87-4b22-abd1-36792c77fa77.png)

nightfly needs some more contrast with the titles and perhaps borders?
![Screenshot from 2023-01-08 10-28-25](https://user-images.githubusercontent.com/3412972/211192313-5b538d6f-3356-404c-b66a-fcccb4f678de.png)

another theme showing Nvim-tree, buffer, and help window.
![Screenshot from 2023-01-08 10-26-07](https://user-images.githubusercontent.com/3412972/211192317-5142646e-6d7d-4c13-8357-cc05783642ad.png)

Note in nightfly the large separation between esp the vertical windows
![Screenshot from 2023-01-08 10-23-52](https://user-images.githubusercontent.com/3412972/211192318-d624c183-92ba-43b9-bce1-79d5c0013c0a.png)

Sorrry for not sending in a merge request.   I'll probably eventually find the right way to do this, but in the mean time, it might also be (subject to personal opinion) an improvement to nightfly.

**Comment by bluz71** [comment]
The existing nightflyWinSeparator option is likely to solve your issue, set it to 2 as explained here:

https://github.com/bluz71/vim-nightfly-colors#nightflywinseparator

**Comment by bluz71** [comment]
Answered.

Note also, it is simple to override certain default theme hightlight groups as [noted here](https://github.com/bluz71/vim-nightfly-colors#overriding-highlights), for example:

```lua
local highlight = vim.api.nvim_set_hl
local custom_highlight = vim.api.nvim_create_augroup("CustomHighlight", {})
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "nightfly",
  callback = function()
     highlight(0, "TelescopeSelectionCaret", { fg = p.red, bg = bg_visual })    
     highlight(0, "TelescopePromptTitle", { fg = p.orange, bg = "NONE" })    
     highlight(0, "TelescopeResultsTitle", { fg = p.orange, bg = "NONE" })    
     highlight(0, "TelescopePreviewTitle", { fg = p.orange, bg = "NONE" })    
     highlight(0, "TelescopePromptCounter", { fg = p.red, bg = "NONE" })    
     highlight(0, "TelescopePreviewHyphen", { fg = p.red, bg = "NONE" }) 
  end,
  group = custom_highlight,
})
```

**Comment by boydkelly** [comment]
Awesome.  Thank you.   Sorry for the noise!

**Comment by bluz71** [comment]
> Awesome. Thank you. Sorry for the noise!

Not noise; I am more than happy to help.

Cheers.
