### ISSUE TITLE
 IncSearch is a bit hard to read

### ISSUE THREAD

**Issue by ray-x** [bluz71/vim-nightfly-colors#48]
Not sure if anyone mentioned it before, but I found the default IncSearch is a bit hard to read. 

![image](https://user-images.githubusercontent.com/1681295/214232658-a01dbf58-8af9-4654-96c9-e734e496f88c.png)

Also the link to LspReferenceText is IncSearch as well. So when my cursor park on a symbol, I am getting this:
![image](https://user-images.githubusercontent.com/1681295/214234267-1062ca94-de20-47f0-adf1-9f9286f12e7e.png)

Feel the contract is a bit too strong... 

Is it possible to darker the guibg of IncSearch and link LspReferenceText to something less obvious? Thanks!

**Comment by bluz71** [comment]
IncSearch for me doesn’t look like that, text is black, which reads well on yellow background. No one has created an issue for this issue, you are the first person.

Could be a terminal interaction. Like bad inheritance. Very strange.

I believe I can tweak things to work around that, wait until tomorrow (it’s night time here where I live).

Let’s fix this.

**Comment by ray-x** [comment]
In fact, I am also wondering how this would work
```vim
hi IncSearch guifg=bg, guibg=...
```

`bg` was not defined anywhere in the vim file. If I change it to 

```vim
hi IncSearch guifg=#111111, guibg=...
```
The highlight will be more legible.

**Comment by bluz71** [comment]
> `bg` was not defined anywhere in the vim file.

`bg` is the defined background color of the `Normal` highlight group. That does work for myself, but not in your case (probably terminal or terminfo related).

Now I explicitly set the `bg` color of `IncSearch` to black, so it should fix your issue.

`LspReferenceText` was not being styled at all;  somehow I just missed it (even though I use Neovim and Neovim LSP). Now I style these highlight groups: `LspReferenceText`, `LspReferenceRead`, `LspReferenceWrite`, `LspCodeLens` and `LspCodeLensSeparator` in addition to `LspSignatureActiveParameter` which I was already styling.

Life should be better now. Many thanks for bringing these to my attention; it is hard to keep on top of every highlight group that needs styling.
