### ISSUE TITLE
Gigsign inline group

### ISSUE THREAD

**Issue by ray-x** [bluz71/vim-nightfly-colors#49]
GitSignsChangeInline/AddInline/DeleteInline are enabled when word diff is set to true for git signs plugin
But sometimes I feel it is a bit distracting when I edit the code. All the code I changed will be highlighted as shown in above screenshot.

![image](https://user-images.githubusercontent.com/1681295/214778646-d2434948-3f8a-4182-9ddb-1c58cb453401.png)

I mean it is great when you want to differ something, but not so great when you edit the code. Is it possible to change the background so it is less obvious?

Thanks!

**Comment by bluz71** [comment]
Yes, that's bad when in edit mode. The original choices were for the preview window (which I use).

I have just committed quick workaround for that which should be good enough here and now.

I need to study Gitsigns more closely to figure what the correct styling is for all the groups available. I think Gitsigns has expanded the styling compared to when I originally added support for the plugin (a long time ago).

**Comment by ray-x** [comment]
Thanks, works much better now.

**Comment by bluz71** [comment]
Good to hear.

Gives me time to implement a better overall solution.

**Comment by bluz71** [comment]
Hello @ray-x,

I have implemented changes to my Gitsigns styling.
In theory you should see no difference with respect to inline word-diff.
Nevertheless, when you have time can you update this theme and make sure there are no regressions.

If there are problems, let me know.

Thanks.
