### ISSUE TITLE
Nvim-navic highlight support

### ISSUE THREAD

**Issue by LucasMartinsVieira** [bluz71/vim-nightfly-colors#50]
I've been using this colorscheme for months now and it's without a doubt the best I've ever used! Congrats.

Lately I started using the [nvim-navic](https://github.com/SmiteshP/nvim-navic) plugin and unfortunately this colorscheme doesn't support nvim-navic highlights yet, can you add it?

**Comment by bluz71** [comment]
Ok, that is a reasonable request.
Give me between a few days and a week, I will get it done.

Best regards.

**Comment by bluz71** [comment]
Implementation done.
Please update.
Hopefully `nvim-navic` will look now look much nicer in your setup.
Let me know if there are any issues.

Best regards.

**Comment by LucasMartinsVieira** [comment]
Thanks for adding it. This improved my Neovim setup a lot! But i have an issue, i think the background color of the gps of ```nvim-navic``` should be the regular bg color of the colorscheme (in moonfly as well), it feels a little bit weird the way it is now. I think would be better.

I will make a Pr on both of your colorschemes repos and you decide if it's better or not.

best regards.

![230226-2229-50](https://user-images.githubusercontent.com/102889079/221451816-712102b8-5022-40a8-a202-9750848a157d.png)
![230226-2230-42](https://user-images.githubusercontent.com/102889079/221451829-9c733ce3-7d2c-416a-8aed-06bec624af1a.png)

**Comment by bluz71** [comment]
`navic` could just as easily be used in the `statusline` as the `winbar`. I need to handle both cases.

The current committed code looks like this:

![Current](https://user-images.githubusercontent.com/11382509/221463655-a7acedcd-e2f7-45bb-ae82-a8cee1071ff8.png)

Your proposed PR looks like this:

![PR](https://user-images.githubusercontent.com/11382509/221463718-49e3fdf1-144c-484a-8c52-ef2c9bbd5727.png)

Pay attention to the `statusline`; notice the black hole where `navic` is emitted (next to `master` branch).

Compare to the current committed code which blends everything together.

At the moment I can't accept the PR; not unless the `statusline` is taken into account.

**Comment by LucasMartinsVieira** [comment]
Okay i understand. Since i do not use ```navic``` in the ```statusline``` i wiil stick with my fork.

thanks for your attention and  your time 

best regards.

**Comment by bluz71** [comment]
Before you go, can you tell me what your `winbar` configuration is; I want to have a look at why your `winbar` looks like this:

![winbar](https://user-images.githubusercontent.com/11382509/221743133-896b4d48-fbfb-41cd-bcaf-3dd59f219f2d.png)

The mix of dark background and lighter background bewilders me since I explicitly set the `winbar` color to something similar to the `statusline` background color (not exactly the same but similar).

Your `winbar` in the above screenshot is something I want to explore.

Cheers.

**Comment by bluz71** [comment]
Actually, I found your `dotfiles`, and I see where you create your own custom `winbar` with specific layout and highlight groups.

After looking at your `winbar`, there is nothing I need to do from my end.

Best regards.
