### ISSUE TITLE
When I use nightfly colors the color become weird, how can I fix it ?

### ISSUE THREAD

**Issue by chi0819** [bluz71/vim-nightfly-colors#54]

**Comment by bluz71** [comment]
You have not provided any details about how to repeat this issue.

Nonetheless, it is quite likely that your issue either is:

- You are not using a true-color terminal, refer [here for details](https://github.com/bluz71/vim-nightfly-colors#true-color-terminals)
- Or, you may be using a broken version of Vim; for example the default version of Vim on macOS does not correctly support `termguicolors`, use Homebrew instead (if this is your issue)

Please check the prerequisites, if you still have an issue then provide a repeatable test case.

Best of luck.
