### ISSUE TITLE
Support new treesitter captures

### ISSUE THREAD

**Issue by tradiff** [bluz71/vim-nightfly-colors#57]
Treesitter was recently updated, which breaks a few colors in vim-nightfly-colors.

Notice of breaking change:
https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583

More information:
https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/

# Screenshots
As an example, here are some screenshots of ruby code ([this file](https://github.com/shahadat3669/blog-app/blob/50e018c762c20fcccbe2c8cf7a0a80b322b5e282/app/controllers/application_controller.rb)) using nvim-treesitter pinned to 0.9.2 vs unpinned.

nvim-treesitter pinned to version="0.9.2":
![nvim-treesitter-0 9 2](https://github.com/bluz71/vim-nightfly-colors/assets/934490/e397ef94-de13-4196-a49e-34a940606564)

nvim-treesitter with no version pin (using current master):
![nvim-treesitter-master](https://github.com/bluz71/vim-nightfly-colors/assets/934490/2342e014-8fa3-4717-b3f7-2e295ee85655)

**Comment by bluz71** [comment]
I now support those new capture names, whilst keeping support for the legacy capture names (since I myself still use stable Neovim `0.9.4`).

Note, this was quite painful.

Please test it out and let me know if you encounter issues; I would not be surprised if have introduced a regression.

Hopefully this is the last time Tree-sitter highlight groups get renamed, this is now the 2nd time.

Best regards.

**Comment by uga-rosa** [comment]
There are fewer colors than before, so there is probably leak.

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights

**Comment by bluz71** [comment]
> There are fewer colors than before, so there is probably leak.

Can you provide more details; please run the `:Inspect` command over the regression.

**Comment by bluz71** [comment]
@uga-rosa,

I found and fixed a few errors. Update again; if there are still issues then run `:Inspect` on top of the regression.

Cheers.

**Comment by uga-rosa** [comment]
It looks okay. Thanks for responding!
