### ISSUE TITLE
[question] italics in markdown

### ISSUE THREAD

**Issue by pedro-augusto-santana** [bluz71/vim-nightfly-colors#58]
hello! first of all, absolutely lovely theme, an even better version of solarized, it perfectly scratched the itch I had over a high-contrast blue dark theme.

quick question, why disable markdown italics?
in the default theme, an italic looks like this:
![image](https://github.com/bluz71/vim-nightfly-colors/assets/48259258/012b7759-ac1b-4efb-a705-1fb56993a883)

which i do concede, `orchid` is a very nice color choice and as you described [here](https://github.com/bluz71/vim-nightfly-colors/pull/33#issuecomment-1179485936) you don't quite like bold fonts (and i wholeheartedly agree, don't like bold text) and `hl link` is faster than the default `hl`

wouldn't setting `g:nightflyItalics` to true enabling it be a better experience?
imho looks quite nice when you patch it
![image](https://github.com/bluz71/vim-nightfly-colors/assets/48259258/34ceae64-a871-43ce-97ba-7ff543fcd6d1)

how do you feel about letting this be a config?
thanks in advance!

**Comment by bluz71** [comment]
I am against bolds, yes.
However, I do use and support italics.

In my Neovim theme for Markdown Tree-siiter I already support italics, so I assume you are talking about Vim and the Tim Pope Markdown syntax?

**Comment by pedro-augusto-santana** [comment]
> I assume you are talking about Vim and the Tim Pope Markdown syntax?

yup, sorry for the omission, I have some custom markdown syntax on a personal plugin (just some specific tokens, no major changes) and as such I disable treesitter on markdown files

yes, this uses the default tpope plugin that comes by default, both screenshots are done with all other plugins disabled (incl. my custom ones and TS), and just nightfly enabled with this simple patch:
![image](https://github.com/bluz71/vim-nightfly-colors/assets/48259258/4769c72f-afa0-4b63-acf6-d73a0f380ca5)

I can use TS just fine and convert my syntax to .scm but my setup is quite convenient, but this is quite a small change, I could put a PR up in a sec if you want

**Comment by bluz71** [comment]
Implemented.

Good suggestion, thanks.
