### ISSUE TITLE
How can I change the ruby method underline?

### ISSUE THREAD

**Issue by chalmagean** [bluz71/vim-nightfly-colors#62]
Hi, I'm trying to either remove or change (to a dark grey background color) the current block/method highlight in a ruby buffer and I've tried the following but I can't seem to get it to work.

```
local status, _ = pcall(vim.cmd, "colorscheme nightfly")

if not status then
  print("Colorscheme not found.")
  return
end

local custom_highlight = vim.api.nvim_create_augroup("CustomHighlight", {})
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "nightfly",
  callback = function()
    -- Hide semantic highlights for methods
    vim.api.nvim_set_hl(0, '@lsp.type.method.ruby', {})

    -- Hide all semantic highlights
    for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
      vim.api.nvim_set_hl(0, group, {})
    end

    -- vim.api.nvim_set_hl(0, "Function", { fg = "#82aaff", bold = true })
  end,
  group = custom_highlight,
})
```

**Comment by bluz71** [comment]
Hello @chalmagean,

I am not entirely sure what you are trying to achieve, but it sounds like you might be running Ruby LSP with Semantic Tokens enabled. That is a combination I am not familiar with.

Nonetheless if I wanted to change the color of a certain token this is what I would do:

- Move cursor to token of interest
- Run `:lua vim.show_pos()` to view the token highlighting name
- Plug that name into the [Overriding Highlights](https://github.com/bluz71/vim-nightfly-colors#overriding-highlights) script

Also, if I were to disable LSP semantic tokens entirely I would do it via LSP attach as documented [here](https://www.reddit.com/r/neovim/comments/zjqquc/how_do_i_turn_off_semantic_tokens/) or when attaching to a LSP client as documented [here](https://vi.stackexchange.com/questions/41931/how-to-disable-semantic-highlighting-for-certain-filetypes-only) (see last answer).

Good luck, I don't think there is much I can do to assist, you will have to debug this at your end.

Best regards.
