### ISSUE TITLE
Add Yazi to the extras

### ISSUE THREAD

**Issue by tkapias** [bluz71/vim-nightfly-colors#63]
I used the tmtheme.xml file from [fly16](https://github.com/bluz71/fly16-bat) to create a flavor for the terminal file manager [Yazi](https://github.com/sxyazi/yazi).

- The Flavor is here : [fly16.yazi](https://github.com/tkapias/fly16.yazi)
- The pull request to add it in the Yazi's flavors repository: [https://github.com/yazi-rs/flavors/pull/29](https://github.com/yazi-rs/flavors/pull/29)

## Suggestion

| Program                               | Extra
|---------------------------------------|-------------------------------------------------
| [Yazi](https://github.com/sxyazi/yazi)        | [fly16.yazi](https://github.com/tkapias/fly16.yazi)

**Comment by bluz71** [comment]
Hello,

[fly16](https://github.com/bluz71/fly16-bat) uses defined terminal color codes (background, red, blue etc) hence works well with both my moonfly & nightfly themes (if they are used as the terminal theme). The 16 refers to the first 16 colors that a terminal uses.

However, your Yazi them directly uses `#RRGGBB` color codes from the nightfly theme, colors such as `#1d3b53` and `#82aaff`; these colors will not look appropriate when moonfly is in effect.

I believe you should rename you repository from `fly16.yazi` to `nightfly.yazi`.

Alternatively, and preferably, is there any way for your Yazi theme to use Terminal colors, such as terminal blue, terminal red etc?

I appreciate the work; however, lets get the finer details sorted out the first being whether your Yazi theme is a nightfly theme or a fly16 theme (two different things).

Best regards.

**Comment by tkapias** [comment]
You are right, I used fly16 because it provides a .tmTheme file, but I failed to see that the values inside were not #RRGGBB.

And I used #RRGGBB in the flavor because using the colors terminal colors by number would only work for users who use nightly or moonfly terminal colors.

Indeed the best solution would be to make 2 themes, one for moonfly and another for fightfly.

I have reworkes my version as [nightfly.yazi](https://github.com/tkapias/nightfly.yazi) with #RRGGBB values in the .tmTheme file.

I will make a new PR at Yazi to replace fly16.yazi.

Do you see some more corrections I should make in [nightfly.yazi](https://github.com/tkapias/nightfly.yazi) so that the result is faithful to nightfly?

**Comment by tkapias** [comment]
I pushed a new [PR](https://github.com/yazi-rs/flavors/pull/30) to replace fly16.yazi with [nightfly.yazi](https://github.com/tkapias/nightfly.yazi).

If you see anything wrong with [nightfly.yazi](https://github.com/tkapias/nightfly.yazi), I will correct it.

**Comment by bluz71** [comment]
Honestly, I can not offer any guidance on whether nightfly.yazi is correct or not.

I trust your judgement on this matter.

Do you propose to make a moonfly.yazi theme?

**Comment by tkapias** [comment]
I will do it for moonfly too another day. I never took a real look at it before, but it would be useful if I get upset with the blue background in nightfly.

**Comment by tkapias** [comment]
I started a repo for [moonfly.yazi](https://github.com/bluz71/vim-moonfly-colors), it needs some modifications to get the bright colors in the right places, when it's done I will PR Yazi for it.

**Comment by bluz71** [comment]
Thanks @tkapias,

Not being a Yazi user myself all I can go on is the screenshots you have added to your `nightfly.yazi` and `moonfly.yazi` repos.

They look good to me.

I have now added links to your Yazi themes in the extras sections of both moonfly & nightfly.

Job done.

Thanks for your interest in my little themes, it is appreciated.

Best regards.

**Comment by bluz71** [comment]
Hi @tkapias,

Can you also upstream your `moonfly.yazi` theme to main Yazi repo?

**Comment by tkapias** [comment]
@bluz71 I pushed moonfly.yazi: https://github.com/yazi-rs/flavors/pull/31
